public class Main {
    public static void main(String[] args) {
        Bus bus1  = new Bus();
        Bus bus2  = new Bus();
        System.out.println("--------PT BUS  S#1-----------");
        System.out.println(bus1.getNumber());
        System.out.println(bus2.getNumber());
        System.out.println("--------Bus S#1----------");
        bus1.setCurrent_passenger(2);
        bus1.left_passenger();
        System.out.println("요금=" + bus1.getBusfare());
        System.out.println("--------Bus S#3----------");
        bus1.setFuel(-50);
        System.out.println("남은 주유량="+bus1.getFuel());
        System.out.println("--------Bus S#5----------");
        bus1.change_status();
        System.out.println("--------Bus S#6----------");
        bus1.setFuel(+10);
        System.out.println(bus1.getStatus());
        System.out.println("남은 주유량="+bus1.getFuel());
        System.out.println("--------Bus S#8----------");
        bus1.change_status();
        System.out.println("--------Bus S#9----------");
        bus1.setCurrent_passenger(45);
        bus1.left_passenger();
        System.out.println("--------Bus S#11----------");
        bus1.setCurrent_passenger(5);
        bus1.left_passenger();
        System.out.println("요금=" + bus1.getBusfare());
        System.out.println("--------Bus S#13----------");
        bus1.setFuel(-55);
        System.out.println("남은 주유량=" + bus1.getFuel());
        bus1.change_status();
        System.out.println("----------------------------------------");
        System.out.println("----------------------------------------");
        Taxi taxi1  = new Taxi();
        Taxi taxi2  = new Taxi();
        System.out.println("--------PT TAXI  S#1-----------");
        System.out.println(taxi1.getNumber());
        System.out.println(taxi2.getNumber());
        System.out.println(taxi1.getFuel());
        System.out.println(taxi1.getStatus());
        System.out.println("--------Taxi S#1----------");
        taxi1.setCurrent_passenger(2);
        taxi1.left_passenger();
        System.out.println("요금 확인=" + taxi1.getTaxifare());
        taxi1.setDestination("서울역");
        System.out.println("목적지=" + taxi1.getDestination());
        taxi1.setTotalkm(2);
        System.out.println("목적지까지 거리=" + taxi1.getTotalkm() + "km");
        taxi1.setTotalearned();
        System.out.println("지불요금="+ taxi1.getTaxiplusfare());
        taxi1.change_status();
        System.out.println("--------Taxi S#3----------");
        taxi1.setFuel(-80);
        System.out.println("남은 주유량=" + taxi1.getFuel());
        System.out.println("누적요금="+taxi1.getTotalearned());
        System.out.println("--------Taxi S#6----------");
        taxi1.setCurrent_passenger(5);
        taxi1.left_passenger();
        System.out.println("--------Taxi S#8----------");
        taxi1.setCurrent_passenger(3);
        taxi1.left_passenger();
        System.out.println("기본요금=" + taxi1.getTaxifare());
        taxi1.setDestination("구로디지털단지역");
        System.out.println("목적지=" + taxi1.getDestination());
        taxi1.setTotalkm(12);
        System.out.println("목적지까지 거리=" + taxi1.getTotalkm() + "km");
        System.out.println("지불요금="+ taxi1.getTaxiplusfare());
        System.out.println("--------Taxi S#10----------");
        taxi1.setFuel(-20);
        System.out.println("남은 주유량=" + taxi1.getFuel());
        taxi1.change_status();
        taxi1.setTotalearned();
        System.out.println("누적요금="+taxi1.getTotalearned());
    }
}